const document = {
  URL: "https://www.baidu.com/"",
activeElement: body
adoptedStyleSheets: []
alinkColor: ""
all: HTMLAllCollection(1221)
anchors: HTMLCollection(12)
applets: HTMLCollection[]
baseURI: ""
bd_ala_form: ()
bgColor: ""
body: body
characterSet: "UTF-8"
charset: "UTF-8"
childElementCount: 1
childNodes: NodeList(3)[html, comment, html]
children: HTMLCollection[html]
compatMode: "CSS1Compat"
contentType: "text/html"
cookie: ""
currentScript: null
defaultView: Window { postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, parent: Window, … }
designMode: "off"
dir: ""
doctype: html
documentElement: html
documentURI: ""
domain: "www.baidu.com"
embeds: HTMLCollection[]
f: (...)
featurePolicy: FeaturePolicy { }
fgColor: ""
firstChild: html
firstElementChild: html
fonts: FontFaceSet { }
forms: HTMLCollection(2)[form#form.fm, form.op_translation_form, form: form#form.fm, f: form#form.fm, bd_ala_form: form.op_translation_form]
fullscreen: false
fullscreenElement: null
fullscreenEnabled: true
head: head
hidden: false
images: HTMLCollection(37)
implementation: DOMImplementation { }
inputEncoding: "UTF-8"
isConnected: true
jQuery1102024527626497113042: 6
lastChild: html
lastElementChild: html
lastModified: "08/30/2019 11:33:39"
linkColor: "#0000cc"
links: HTMLCollection(260)
location: Location { replace: ƒ, href: "https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=b…D%E5%9B%BD%E7%9C%81%E5%B8%82%20%E5%9D%90%E6%A0%87", ancestorOrigins: DOMStringList, origin: "https://www.baidu.com", protocol: "https:", … }
nextSibling: null
nodeName: "#document"
nodeType: 9
nodeValue: null
onabort: null
onauxclick: null
onbeforecopy: null
onbeforecut: null
onbeforepaste: null
onblur: null
oncancel: null
oncanplay: null
oncanplaythrough: null
onchange: null
onclick: null
onclose: null
oncontextmenu: null
oncopy: null
oncuechange: null
oncut: null
ondblclick: null
ondrag: null
ondragend: null
ondragenter: null
ondragleave: null
ondragover: null
ondragstart: null
ondrop: null
ondurationchange: null
onemptied: null
onended: null
onerror: null
onfocus: null
onfreeze: null
onfullscreenchange: null
onfullscreenerror: null
ongotpointercapture: null
oninput: null
oninvalid: null
onkeydown: null
onkeypress: null
onkeyup: null
onload: null
onloadeddata: null
onloadedmetadata: null
onloadstart: null
onlostpointercapture: null
onmousedown: null
onmouseenter: null
onmouseleave: null
onmousemove: null
onmouseout: null
onmouseover: null
onmouseup: null
onmousewheel: null
onpaste: null
onpause: null
onplay: null
onplaying: null
onpointercancel: null
onpointerdown: null
onpointerenter: null
onpointerleave: null
onpointerlockchange: null
onpointerlockerror: null
onpointermove: null
onpointerout: null
onpointerover: null
onpointerup: null
onprogress: null
onratechange: null
onreadystatechange: null
onreset: null
onresize: null
onresume: null
onscroll: null
onsearch: null
onsecuritypolicyviolation: null
onseeked: null
onseeking: null
onselect: null
onselectionchange: null
onselectstart: null
onstalled: null
onsubmit: null
onsuspend: null
ontimeupdate: null
ontoggle: null
onvisibilitychange: null
onvolumechange: null
onwaiting: null
onwebkitfullscreenchange: null
onwebkitfullscreenerror: null
onwheel: null
ownerDocument: null
parentElement: null
parentNode: null
pictureInPictureElement: null
pictureInPictureEnabled: true
plugins: HTMLCollection[]
pointerLockElement: null
previousSibling: null
readyState: "complete"
referrer: "https://www.baidu.com/"
rootElement: null
scripts: HTMLCollection(30)
scrollingElement: html
styleSheets: StyleSheetList { 0: CSSStyleSheet, 1: CSSStyleSheet, 2: CSSStyleSheet, 3: CSSStyleSheet, 4: CSSStyleSheet, 5: CSSStyleSheet, 6: CSSStyleSheet, 7: CSSStyleSheet, 8: CSSStyleSheet, 9: CSSStyleSheet, 10: CSSStyleSheet, 11: CSSStyleSheet, 12: CSSStyleSheet, length: 13 }
textContent: null
title: "百度fan_百度搜索"
visibilityState: "visible"
vlinkColor: ""
wasDiscarded: false
webkitCurrentFullScreenElement: null
webkitFullscreenElement: null
webkitFullscreenEnabled: true
webkitHidden: false
webkitIsFullScreen: false
webkitVisibilityState: "visible"
write: ƒ()
writeln: ƒ()
xmlEncoding: null
xmlStandalone: false
xmlVersion: null
get bd_ala_form: ƒ()
get f: ƒ()
__proto__: HTMLDocument
}